AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer with 2 Subnets

Parameters:
  VpcId:
    Type: String

  Subnet1Id:
    Type: String

  Subnet2Id:
    Type: String

  ALBSecurityGroupId:
    Type: String

  ALBName:
    Type: String
    Default: AnishALB

  TargetGroupName:
    Type: String
    Default: AnishTargetGroup

  ListenerPort:
    Type: Number
    Default: 80

  TargetPort:
    Type: Number
    Default: 80

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ALBName
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1Id
        - !Ref Subnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      VpcId: !Ref VpcId
      Port: !Ref TargetPort
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      HealthCheckProtocol: HTTP

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: !Ref ListenerPort
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
  LoadBalancerDNS:
    Value: !GetAtt ALB.DNSName
