AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Group with Target Tracking

Parameters:
  LaunchTemplateId:
    Type: String

  LaunchTemplateVersion:
    Type: String

  SubnetId:
    Type: String

  TargetGroupArn:
    Type: String

  MinSize:
    Type: Number
    Default: 1

  MaxSize:
    Type: Number
    Default: 2

  DesiredCapacity:
    Type: Number
    Default: 1

  HealthCheckGracePeriod:
    Type: Number
    Default: 180

  TargetCPUUtilization:
    Type: Number
    Default: 50.0

Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetId
      TargetGroupARNs:
        - !Ref TargetGroupArn
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      HealthCheckType: EC2
      HealthCheckGracePeriod: !Ref HealthCheckGracePeriod

  ScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      EstimatedInstanceWarmup: !Ref HealthCheckGracePeriod
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref TargetCPUUtilization

Outputs:
  AutoScalingGroupName:
    Value: !Ref AutoScalingGroup
